package lk.sliit.itpmproject.dao;

public enum DAOTypes {
    TIME_TABLE, CONSECUTIVE_SESSIONS,  QUERY, SESSION_MANAGE_NA_LEC, ADD_SESSIONS, ADD_WORKING_DAYS_DAO, ADD_STUDENT, ADD_LECTURER,
    ADD_LOCATIONS, ADD_TAG, ADD_SUBJECT, STUDENT_STATICS

}
